name: wxauto_mgt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=22.3
  - pip:
    - PySide6>=6.4.0
    - aiohttp>=3.8.3
    - asyncio>=3.4.3
    - aiosqlite>=0.17.0
    - cryptography>=38.0.0
    - loguru>=0.6.0
    - pytest>=7.2.0
    - pytest-asyncio>=0.20.0
    - pytest-qt>=4.2.0
    - black>=22.10.0
    - isort>=5.10.1
    - pyinstaller>=5.6.0 